name: Pull request workflow

on: pull_request

jobs:
  format-check:
    name: Checking formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install node_modules
        run: yarn

      - name: Run Prettier check
        run: yarn run format:check

  test-deploy:
    name: Test deploy
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install node_modules
        run: yarn

      - name: Run build
        run: yarn run build
